# conf.yml
n_envs: 2

# Hyperparameters specific to the training algorithm
tqc:
  policy: "MultiInputPolicy"
  learning_rate: 3e-4
  buffer_size: 10000  # Reduce buffer size
  learning_starts: 10000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  action_noise: null
  optimize_memory_usage: True
  policy_kwargs: {}
  verbose: 1
  seed: null
  device: "auto"


ReachCube-v0:
  n_timesteps: !!float 1e7
  policy: 'MultiInputPolicy'
  frame_stack: 1  # Disable frame stacking if not needed
  use_sde: True
