repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: [--fix, --line-length, '127']
      - id: ruff-format
        args: [--line-length, '127']
